field: 6e6fa4a9-95b2-4046-83e7-45112f9100ef # Content Builder
fieldLayouts:
  ecb4a967-edd1-44c0-9909-768bbde6610a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50384c13-4549-4cc5-9347-8f3518d5a786 # Codes
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90d1adb8-3374-4d78-84c8-f09b66384fcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1f16308-1eec-4623-b5c2-d03b1575bee8
        userCondition: null
fields:
  50384c13-4549-4cc5-9347-8f3518d5a786: # Codes
    columnSuffix: aygvuorq
    contentColumnType: text
    fieldGroup: null
    handle: codes
    instructions: null
    name: Codes
    searchable: false
    settings:
      addRowLabel: 'Add a response code'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Status Code'
                -
                  - handle
                  - code
                -
                  - width
                  - ''
                -
                  - type
                  - number
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Description
                -
                  - handle
                  - description
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults: null
      maxRows: null
      minRows: 1
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: httpResponseCodes
name: 'HTTP Response Codes'
sortOrder: 12
