field: 6e6fa4a9-95b2-4046-83e7-45112f9100ef # Content Builder
fieldLayouts:
  f27ec331-5be4-4d4f-97c2-73530d2b198c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 541c48e6-7066-467a-b82e-35cf97c36018 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36a19171-d2c9-4f20-93eb-5687bcdf50cb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 605a3b26-bb19-47ff-b6e9-42e0713674b2
        userCondition: null
fields:
  541c48e6-7066-467a-b82e-35cf97c36018: # Copy
    columnSuffix: uoujtery
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: info
name: 'Info Bubble'
sortOrder: 9
