field: 6e6fa4a9-95b2-4046-83e7-45112f9100ef # Content Builder
fieldLayouts:
  8e42e3b5-b6a8-419b-b1b0-4d96f5b126c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c4cc8873-9931-4003-ae88-313a02628139 # Attributes
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f0791cd-fc5b-41bb-9035-83b3b660e2fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62e99999-1372-432f-999d-6da36e2fc721
        userCondition: null
fields:
  c4cc8873-9931-4003-ae88-313a02628139: # Attributes
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: attrs
    instructions: null
    name: Attributes
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1296851191
      columns:
        __assoc__:
          -
            - 0f7cb40f-6787-4404-bcb2-7f95ac9a7ef7 # Attribute Name
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 08535bb1-52ce-4d27-9908-aa5bc8555b1f # Description
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - db573abc-435e-4936-bc53-6a2c534407cf # Attribute Type
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 43f5030a-2a17-47fc-aa73-f69590cbcbb6 # Nullable
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - dae6d34d-9d8e-405c-9bae-828a53bfaae3 # Required
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_10_attrs}}'
      fieldLayout: row
      maxRows: null
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add an Attribute'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: quickAttributeList
name: 'Quick Attribute List'
sortOrder: 11
