field: 6e6fa4a9-95b2-4046-83e7-45112f9100ef # Content Builder
fieldLayouts:
  d566cc63-4a1a-45da-8244-5da3b31b9c32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed0b9ed1-e518-4124-a845-feb55ea4d219 # Space
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84b2ffeb-8e2e-49de-b394-a64aa8cc7bd2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27124a22-6253-46d8-b65b-515bad206cb3
        userCondition: null
fields:
  ed0b9ed1-e518-4124-a845-feb55ea4d219: # Space
    columnSuffix: yyotodmc
    contentColumnType: string(6)
    fieldGroup: null
    handle: space
    instructions: null
    name: Space
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - 'Extra Small'
            -
              - value
              - mb-0.5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - mb-1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - mb-2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - mb-4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: spacer
name: Spacer
sortOrder: 3
