fieldLayouts:
  4415779e-6a1d-4be4-9bd6-6c25c2e833c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4c10e61b-d3ff-4dcb-9dc0-dfb6a8646772
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e6fa4a9-95b2-4046-83e7-45112f9100ef # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86432596-2e95-4f29-8315-859ee157a964
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 480b8ac7-5299-4212-85ff-9700c2e0ff61
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 4ae43450-5bb3-45ec-ac20-3c7ce959e4c8 # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
