fieldLayouts:
  09473af9-dd62-429d-886a-3517a3502b62:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e261ffe-32ca-413f-9d63-286a3a37db6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 318b56b7-c9ce-4515-9b4e-9679a3de623e # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43fe2046-d76f-4c6d-ae39-6bccd79005d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6994a009-5803-49ca-82a6-14950e385398 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e36fa93f-56e0-4ae6-9620-f5d1866ebce3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b34ab1f0-ed3b-43b4-ab29-26e2cda48b8d # Attributes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d7a3544-8f6e-4d47-9894-12702f22a0de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8fc3486-32df-4618-b065-51b69bbe9a63
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 65c192b0-bfac-420f-ae24-e4279c8eff6a # Request Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ce60811-36db-46ac-9894-e05bd4c40571
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 766c14db-4949-4dca-b33e-d65c21df14b8 # Request
            instructions: 'An example cURL request.'
            label: Example
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 928b3d08-e2dc-4a76-9c33-2ead82c51b56
            userCondition: null
            warning: null
            width: 100
        name: Request
        uid: 792f6f08-0521-4a25-9d33-a9fa444a40a8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bfbab645-8672-4ad9-a43c-6e12cc5cb5cf # Response Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6166633-5775-40e2-9a8c-245a3443e1be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68ad52be-0e32-4692-8fd0-aea664b34e56 # Response
            instructions: 'An example JSON response.'
            label: Example
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5174b0eb-95e4-4ccb-823f-255b701c590e
            userCondition: null
            warning: null
            width: 100
        name: Response
        uid: fa6de91a-2786-447a-b65e-fb5170822ed5
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: ef3f6698-acc4-4e2f-8cee-9f4b9763e3f7 # Models
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
