fieldLayouts:
  78439d0c-b0c9-4a07-bb27-c137cdb4a7b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 32127d69-d44f-4b53-b112-49849f46c38f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ffcd89a0-af9f-49db-bd14-2093ebd1a82c # Document
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f63ab36-89dd-4b3a-8e28-9fed04a82bc7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 510304a3-2f19-4036-902c-02f8cc612745
        userCondition: null
handle: document
hasTitleField: true
name: Document
section: 57ea729e-f774-4839-b91f-25e177e8491d # Navigation
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
