columnSuffix: lgylaffs
contentColumnType: text
fieldGroup: 43074a37-f4ec-4832-be0a-ad3c54463f59 # Common
handle: description
instructions: null
name: Description
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 85eefa55-3764-4be1-baa1-3ca9a7b50c8f # Description
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
