columnSuffix: weohpdhr
contentColumnType: text
fieldGroup: 43074a37-f4ec-4832-be0a-ad3c54463f59 # Common
handle: response
instructions: 'An example JSON response.'
name: Response
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 8
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
