dateModified: 1711211254
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - dateCreated
        - dateUpdated
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:4ae43450-5bb3-45ec-ac20-3c7ce959e4c8' # Pages
      tableAttributes:
        - dateCreated
        - dateUpdated
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:57ea729e-f774-4839-b91f-25e177e8491d' # Navigation
      tableAttributes:
        - type
        - 'field:f8d80a29-a9a9-40ad-9920-1c79d80cf3fc' # Hash
        - 'field:56a62ed8-7abe-4da2-b0cf-c1f02378261e' # Page Jump Method
      type: native
    -
      heading: Data
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:3c1ffc2c-34c0-445d-b181-60d4ea2082e8' # Data Types
      tableAttributes: '-'
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:d4c91da5-7fb0-46c8-94c1-43276587afc1' # Attributes
      tableAttributes:
        - 'field:ea9984fd-afdf-47af-9ee7-309821b7822e' # Description
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:ef3f6698-acc4-4e2f-8cee-9f4b9763e3f7' # Models
      tableAttributes: '-'
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:630d0468-3baf-4896-93cd-b29ddd19b6f2' # Endpoints
      tableAttributes:
        - 'field:318b56b7-c9ce-4515-9b4e-9679a3de623e' # Heading
        - 'field:8c7132a4-f1ce-4d24-9bae-a52d0416f425' # Returns
      type: native
email:
  fromEmail: codingwithkyle@gmail.com
  fromName: 'API Docs'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a5a1671-34f4-454d-ba37-7d78f64878f2: Default # Default
    0c48af99-98cb-45a8-ad43-8c4ef573bf95: Copy # Copy
    0f7cb40f-6787-4404-bcb2-7f95ac9a7ef7: 'Attribute Name' # Attribute Name
    00f96a90-97e5-4fc2-840b-7ba41b0e961f: Default # Default
    1e3692f5-bd58-4159-bdf7-a6a8dc72297a: Default # Default
    2a76d3d5-243e-45d4-b0e8-0eeebcad8071: Method # Method
    2b259f21-d9eb-4df7-a4b3-cd0661136e0c: Introduction # Introduction
    3c1ffc2c-34c0-445d-b181-60d4ea2082e8: 'Data Types' # Data Types
    3e3fab31-2146-41f5-8ddc-3dc16f7acf6a: Default # Default
    3f6a94d7-65f7-4920-a1b0-c9547b69d058: Size # Size
    4ae43450-5bb3-45ec-ac20-3c7ce959e4c8: Pages # Pages
    4d47407e-1323-4801-9555-13aff3d103c3: Code # Code
    5a0ce0ae-4e46-44ea-bfa9-13daec1197f7: 'Quick Attribute List' # Quick Attribute List
    6c3a98f5-afa2-44f6-8c21-b5592ccabcaf: Heading # Heading
    6e6fa4a9-95b2-4046-83e7-45112f9100ef: 'Content Builder' # Content Builder
    6e261858-b029-44bf-9126-30c95b07c345: Default # Default
    6f75b70b-707b-4336-878b-38d71e7622a2: 'Info Bubble' # Info Bubble
    8bb41c00-83d8-462d-8dcf-20d29ae8d103: Line # Line
    8c7132a4-f1ce-4d24-9bae-a52d0416f425: Returns # Returns
    9cc44862-caaf-4422-a3aa-6c5152b04f68: Introduction # Introduction
    43f5030a-2a17-47fc-aa73-f69590cbcbb6: Nullable # Nullable
    48d1c729-c86d-46d1-bc0b-89ded083238b: 'API Docs' # API Docs
    56a62ed8-7abe-4da2-b0cf-c1f02378261e: 'Page Jump Method' # Page Jump Method
    57ea729e-f774-4839-b91f-25e177e8491d: Navigation # Navigation
    65c192b0-bfac-420f-ae24-e4279c8eff6a: 'Request Label' # Request Label
    68ad52be-0e32-4692-8fd0-aea664b34e56: Response # Response
    76a1eb0d-c841-4291-8e44-e29d00f39f61: Model # Model
    77d42b50-b88b-4fe8-b2d8-90a82ce533a7: 'Public Schema' # Public Schema
    85eefa55-3764-4be1-baa1-3ca9a7b50c8f: Description # Description
    148be2a9-d20b-475c-bc39-704f8328148b: Document # Document
    302cd103-8bd6-4a27-8cd6-aa9d74e695cf: Model # Model
    318b56b7-c9ce-4515-9b4e-9679a3de623e: Heading # Heading
    342be9bc-3d31-4bbd-9df5-2b9c9a421c77: 'API Docs' # API Docs
    471d6c63-18de-4f5e-8b33-1c9bd74cfb4b: 'Page Jump' # Page Jump
    541c48e6-7066-467a-b82e-35cf97c36018: Copy # Copy
    591d6ef7-a9bc-4545-990e-cbb629ec6fa7: Simple # Simple
    608c9020-a77c-4f7e-82e1-01de53506434: Source # Source
    630d0468-3baf-4896-93cd-b29ddd19b6f2: Endpoints # Endpoints
    766c14db-4949-4dca-b33e-d65c21df14b8: Request # Request
    808cb1eb-e6ac-4814-b74c-5a88f2c744c0: Document # Document
    6994a009-5803-49ca-82a6-14950e385398: Copy # Copy
    08535bb1-52ce-4d27-9908-aa5bc8555b1f: Description # Description
    43074a37-f4ec-4832-be0a-ad3c54463f59: Common # Common
    50384c13-4549-4cc5-9347-8f3518d5a786: Codes # Codes
    53286e64-7dcd-43e3-9291-490bfb17e03e: Endpoint # Endpoint
    300641b7-dbf8-441b-bab6-25e8dafbc1ce: Label # Label
    9629787a-5dee-41d6-922f-230e8fb6a202: Method # Method
    54326662-f4a4-437b-b7fd-78f20ba2837f: Nullable # Nullable
    a2fd2914-e806-4b60-80fa-65fe0b9570dc: Group # Group
    a4fe56d2-aaa3-468d-8b8b-620afbf8a007: Required # Required
    ad14ea4f-2b83-4e1e-b17f-5d5f623a7203: Endpoint # Endpoint
    b06b61ed-5f4b-450c-b3a6-da2c3c4dbf49: 'Enum values' # Enum values
    b34ab1f0-ed3b-43b4-ab29-26e2cda48b8d: Attributes # Attributes
    bdd28828-58d6-451a-a51b-9d39dfdae491: Route # Route
    bf5a4bc0-6714-4e23-b399-4ee2bc062193: Route # Route
    bfbab645-8672-4ad9-a43c-6e12cc5cb5cf: 'Response Label' # Response Label
    c4cc8873-9931-4003-ae88-313a02628139: Attributes # Attributes
    c8a5fe09-5f30-4340-a00e-dbdc8bdd35d0: Spacer # Spacer
    cd37dcf3-f5e5-4837-bc90-d833555711e7: 'cURL Request' # cURL Request
    d4b56bed-46c0-4a26-b619-c4ced7149e05: Link # Link
    d4c91da5-7fb0-46c8-94c1-43276587afc1: Attributes # Attributes
    d16ffa2e-4488-42f2-8dfb-f3b2489144c7: Model # Model
    d599dc56-2ff5-4ff4-a4a5-2e4d68eaa6be: Parameters # Parameters
    d4872f23-314a-4203-bcaf-7327ae9a3cc5: 'HTTP Response Codes' # HTTP Response Codes
    dae6d34d-9d8e-405c-9bae-828a53bfaae3: Required # Required
    db573abc-435e-4936-bc53-6a2c534407cf: 'Attribute Type' # Attribute Type
    dc0960af-d86a-44b3-b733-5f36d85aaf7a: Source # Source
    e6c9568f-4e6b-439c-a4d5-de411bc279eb: 'Rich Text' # Rich Text
    e82ee02b-f803-413b-ab3b-47c6358b6987: Language # Language
    e1433b59-67f3-4eb9-b475-e3e7d517ec85: 'Attribute Name' # Attribute Name
    e3016ab9-a15c-4eed-87c5-285e39b4bc52: Description # Description
    ea3314e9-ff4c-47e6-b687-a81778869318: Type # Type
    ea9984fd-afdf-47af-9ee7-309821b7822e: Description # Description
    ec1511b1-1f46-424a-8220-20e77ca7f6d8: Text # Text
    ed0b9ed1-e518-4124-a845-feb55ea4d219: Space # Space
    ef3f6698-acc4-4e2f-8cee-9f4b9763e3f7: Models # Models
    f076fe8e-1578-4830-8ab1-36aec23bd489: Space # Space
    f8d80a29-a9a9-40ad-9920-1c79d80cf3fc: Hash # Hash
    f45ab33e-627b-4341-b88a-3822e8a485e5: 'Button Mode' # Button Mode
    f807dfab-eb24-48b7-8ee9-243d1e3cb116: 'External URL' # External URL
    ffcd89a0-af9f-49db-bd14-2093ebd1a82c: Document # Document
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: 'API Docs'
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
