defaultPlacement: end
enableVersioning: true
handle: dataTypes
name: 'Data Types'
propagationMethod: all
siteSettings:
  342be9bc-3d31-4bbd-9df5-2b9c9a421c77: # API Docs
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
