defaultPlacement: end
enableVersioning: true
handle: introduction
name: Introduction
propagationMethod: all
siteSettings:
  342be9bc-3d31-4bbd-9df5-2b9c9a421c77: # API Docs
    enabledByDefault: true
    hasUrls: true
    template: introduction/_entry
    uriFormat: __home__
type: single
